#!/bin/sh

##### AUTOSTART PART

# Run keybindings daemon (the '-m' option is important for non-qwerty
# keyboards) --> See the man page for precisions
sxhkd -m 1 &

# Set frame rate and resolution
xrandr --output DP-4 --mode 1920x1080 --rate 144

# Run polybar
$HOME/.config/polybar/launch.sh &

# Run notification daemon
dunst --config $HOME/.config/dunst/dunstrc &

# Run the compositor
picom --config $HOME/.config/picom/picom.conf &

# Run polkit daemon if doesn't started.
[ -n "$(pidof xfce-polkit)" ] || /usr/lib/xfce-polkit/xfce-polkit &

# Run the power manager
xfce4-power-manager &

# Run mpd if it is not already running
[ -n "$(pidof mpd)" ] || mpd &

# Execute bspwm-specific scripts
bspfloat &

# Start X wallpaper
feh --no-fehbg --bg-fill $HOME/.local/share/wallpapers/mountain_tl.jpg

# Fix cursor
xsetroot -cursor_name left_ptr 

# Extend the path with binaries in bspwm's folder
export PATH="${PATH}:${HOME}/.config/bspwm/bin"

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }

##### WINDOWS

bspc monitor -d 1 2 3 4 5 6  

rule -a kitty                       follow=on focus=on
rule -a code                        follow=on focus=on
rule -a firefox                     follow=on focus=on
rule mpv                            state=floating
rule feh                            state=floating

##### GENERAL

config top_padding 26
config border_width 2
config window_gap 10
config split_ratio 0.50

config borderless_monocle true
config gapless_monocle true
config focus_follows_pointer true

bspc config normal_border_color "#111111"
bspc config focused_border_color "#111111"
config presel_feedback_color "#111111"
pkill borders ; borders &

